# Form implementation generated from reading ui file '/Users/macbookair/DESARROLLO/ipatool-pyclient/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_Search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Search.setObjectName("lineEdit_Search")
        self.horizontalLayout_2.addWidget(self.lineEdit_Search)
        self.pushButton_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout_2.addWidget(self.pushButton_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableView_search_results = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_search_results.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView_search_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView_search_results.setObjectName("tableView_search_results")
        self.verticalLayout_2.addWidget(self.tableView_search_results)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_download = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_download.setObjectName("pushButton_download")
        self.horizontalLayout.addWidget(self.pushButton_download)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 30))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(parent=self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCargar = QtGui.QAction(parent=MainWindow)
        self.actionCargar.setObjectName("actionCargar")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAutenticar_usuario_sin_2FA = QtGui.QAction(parent=MainWindow)
        self.actionAutenticar_usuario_sin_2FA.setObjectName("actionAutenticar_usuario_sin_2FA")
        self.menuArchivo.addAction(self.actionAutenticar_usuario_sin_2FA)
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_Search.setPlaceholderText(_translate("MainWindow", "App to search: Whatsapp, Instagram"))
        self.pushButton_search.setText(_translate("MainWindow", "Buscar"))
        self.pushButton_download.setText(_translate("MainWindow", "Descargar"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionCargar.setText(_translate("MainWindow", "Cargar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionAutenticar_usuario_sin_2FA.setText(_translate("MainWindow", "Autenticar usuario sin 2FA"))
